add beacon_node_light_client_data_* variables
status-im/infra-role-beacon-node-linux pull request #7
Opened 2022-03-16 15:50 UTC by etan-status

To control the `--serve-light-client-data` and
`--import-light-client-data` flags.

Note: These new flags are only available on `unstable` at this time. `stable` does not support them yet.

2022-03-17 08:59 UTC, jakubgs commented
Wait, what format data does the `--import-light-client-data=` flag expect?

2022-03-17 11:53 UTC, etan-status commented
https://github.com/status-im/nimbus-eth2/blob/unstable/beacon_chain/conf.nim#L438

One of:
- `none`
- `only-new`
- `full`
- `on-demand`

It's only on `unstable` so far, not yet available on `testing` or `stable`.

2022-03-17 12:54 UTC, jakubgs requested changes
If this flag is not available in other branches then it needs to be conditional, otherwise it will break other nodes which do not support these flags when Ansible is run.

2022-03-25 15:44 UTC, etan-status commented
- Use common prefix `beacon_node_light_client_data_` for new variables.

2022-03-25 15:56 UTC, jakubgs approved these changes

2022-03-25 15:57 UTC, merged